// Generated by scripts/build-i18n.mjs — DO NOT EDIT MANUALLY
globalThis.VC_MESSAGES = {
  "Navigation": {
    "en": "Navigation",
    "cs": "Navigace",
    "de": "Navigation",
    "es": "Navegación",
    "fr": "Navigation",
    "pt": "Navegação",
    "zh": "导航",
    "hi": "नेविगेशन",
    "ar": "التنقل",
    "bn": "নেভিগেশন",
    "ru": "Навигация",
    "ja": "ナビゲーション",
    "id": "Navigasi"
  },
  "← Valheim Companion": {
    "en": "← Valheim Companion",
    "cs": "← Valheim Companion",
    "de": "← Valheim Companion",
    "es": "← Valheim Companion",
    "fr": "← Valheim Companion",
    "pt": "← Valheim Companion",
    "zh": "← Valheim Companion",
    "hi": "← Valheim Companion",
    "ar": "← Valheim Companion",
    "bn": "← Valheim Companion",
    "ru": "← Valheim Companion",
    "ja": "← Valheim Companion",
    "id": "← Valheim Companion"
  },
  "Language": {
    "en": "Language",
    "cs": "Jazyk",
    "de": "Sprache",
    "es": "Idioma",
    "fr": "Langue",
    "pt": "Idioma",
    "zh": "语言",
    "hi": "भाषा",
    "ar": "اللغة",
    "bn": "ভাষা",
    "ru": "Язык",
    "ja": "言語",
    "id": "Bahasa"
  },
  "Auto (browser)": {
    "en": "Auto (browser)",
    "cs": "Automaticky (prohlížeč)",
    "de": "Automatisch (Browser)",
    "es": "Automático (navegador)",
    "fr": "Auto (navigateur)",
    "pt": "Automático (navegador)",
    "zh": "自动（浏览器）",
    "hi": "स्वचालित (ब्राउज़र)",
    "ar": "تلقائي (المتصفح)",
    "bn": "স্বয়ংক্রিয় (ব্রাউজার)",
    "ru": "Авто (браузер)",
    "ja": "自動（ブラウザー）",
    "id": "Otomatis (browser)"
  },
  "Fan project, not affiliated with Iron Gate.": {
    "en": "Fan project, not affiliated with Iron Gate.",
    "cs": "Fanouškovský projekt bez spojení s Iron Gate.",
    "de": "Fanprojekt, nicht mit Iron Gate verbunden.",
    "es": "Proyecto de fans, sin afiliación con Iron Gate.",
    "fr": "Projet de fans, sans affiliation avec Iron Gate.",
    "pt": "Projeto de fãs, sem vínculo com a Iron Gate.",
    "zh": "粉丝项目，与 Iron Gate 无关联。",
    "hi": "प्रशंसक परियोजना, Iron Gate से संबद्ध नहीं।",
    "ar": "مشروع معجبين، غير تابع لـ Iron Gate.",
    "bn": "ভক্তদের প্রকল্প, Iron Gate-এর সঙ্গে সম্পর্কিত নয়।",
    "ru": "Фанатский проект, не связан с Iron Gate.",
    "ja": "ファンによるプロジェクト。Iron Gate とは関係ありません。",
    "id": "Proyek penggemar, tidak berafiliasi dengan Iron Gate."
  },
  "Free, ad-free and made in my spare time.": {
    "en": "Free, ad-free and made in my spare time.",
    "cs": "Zdarma, bez reklam a vytvořeno ve volném čase.",
    "de": "Kostenlos, werbefrei und in meiner Freizeit erstellt.",
    "es": "Gratis, sin publicidad y hecho en mi tiempo libre.",
    "fr": "Gratuit, sans publicité et créé sur mon temps libre.",
    "pt": "Gratuito, sem anúncios e feito no meu tempo livre.",
    "zh": "免费无广告，利用业余时间开发。",
    "hi": "निःशुल्क, विज्ञापन-मुक्त और मेरे खाली समय में निर्मित।",
    "ar": "مجاني وبدون إعلانات ومصنوع في وقت فراغي.",
    "bn": "সম্পূর্ণ বিনামূল্যে, বিজ্ঞাপনহীন এবং অবসরে তৈরি।",
    "ru": "Бесплатно, без рекламы и создано в свободное время.",
    "ja": "完全無料・広告なし・個人の趣味で制作。",
    "id": "Gratis, bebas iklan, dan dibuat di waktu luang saya."
  },
  "Buy Me a Coffee at ko-fi.com": {
    "en": "Buy Me a Coffee at ko-fi.com",
    "cs": "Koupit mi kávu na ko-fi.com",
    "de": "Kauf mir einen Kaffee auf ko-fi.com",
    "es": "Invítame a un café en ko-fi.com",
    "fr": "Offrez-moi un café sur ko-fi.com",
    "pt": "Pague-me um café no ko-fi.com",
    "zh": "在 ko-fi.com 上请我喝杯咖啡",
    "hi": "ko-fi.com पर मुझे कॉफ़ी पिलाएँ",
    "ar": "اشترِ لي قهوة عبر ko-fi.com",
    "bn": "ko-fi.com-এ আমাকে একটি কফি দিন",
    "ru": "Купить мне кофе на ko-fi.com",
    "ja": "ko-fi.com でコーヒーを支援する",
    "id": "Beli saya kopi di ko-fi.com"
  },
  "Cancel": {
    "en": "Cancel",
    "cs": "Zrušit",
    "de": "Abbrechen",
    "es": "Cancelar",
    "fr": "Annuler",
    "pt": "Cancelar",
    "zh": "取消",
    "hi": "रद्द करें",
    "ar": "إلغاء",
    "bn": "বাতিল",
    "ru": "Отмена",
    "ja": "キャンセル",
    "id": "Batal"
  },
  "Data:": {
    "en": "Data:",
    "cs": "Data:",
    "de": "Daten:",
    "es": "Datos:",
    "fr": "Données :",
    "pt": "Dados:",
    "zh": "数据：",
    "hi": "डेटा:",
    "ar": "البيانات:",
    "bn": "তথ্য:",
    "ru": "Данные:",
    "ja": "データ：",
    "id": "Data:"
  },
  "Share / transfer progress": {
    "en": "Share / transfer progress",
    "cs": "Sdílet / přenést postup",
    "de": "Fortschritt teilen / übertragen",
    "es": "Compartir / transferir progreso",
    "fr": "Partager / transférer la progression",
    "pt": "Compartilhar / transferir progresso",
    "zh": "分享 / 转移进度",
    "hi": "प्रगति साझा / स्थानांतरित करें",
    "ar": "مشاركة / نقل التقدم",
    "bn": "অগ্রগতি শেয়ার / স্থানান্তর করুন",
    "ru": "Поделиться / перенести прогресс",
    "ja": "進行状況を共有 / 転送",
    "id": "Bagikan / pindahkan kemajuan"
  },
  "Reset progress": {
    "en": "Reset progress",
    "cs": "Resetovat postup",
    "de": "Fortschritt zurücksetzen",
    "es": "Restablecer progreso",
    "fr": "Réinitialiser la progression",
    "pt": "Redefinir progresso",
    "zh": "重置进度",
    "hi": "प्रगति रीसेट करें",
    "ar": "إعادة ضبط التقدم",
    "bn": "অগ্রগতি রিসেট করুন",
    "ru": "Сбросить прогресс",
    "ja": "進行状況をリセット",
    "id": "Atur ulang kemajuan"
  },
  "Progress URL": {
    "en": "Progress URL",
    "cs": "URL postupu",
    "de": "Fortschritts-URL",
    "es": "URL del progreso",
    "fr": "URL de progression",
    "pt": "URL do progresso",
    "zh": "进度链接",
    "hi": "प्रगति का URL",
    "ar": "رابط التقدم",
    "bn": "অগ্রগতির URL",
    "ru": "Ссылка на прогресс",
    "ja": "進行状況のURL",
    "id": "URL kemajuan"
  },
  "If it helped your run, you can buy me a coffee.": {
    "en": "If it helped your run, you can buy me a coffee.",
    "cs": "Pokud ti pomohl při hraní, můžeš mi koupit kávu.",
    "de": "Wenn es dir beim Spielen geholfen hat, kannst du mir einen Kaffee spendieren.",
    "es": "Si te ayudó en tu partida, puedes invitarme a un café.",
    "fr": "Si ce projet vous a aidé, vous pouvez m'offrir un café.",
    "pt": "Se ajudou na sua aventura, você pode me pagar um café.",
    "zh": "如果对你的冒险有帮助，可以请我喝杯咖啡。",
    "hi": "अगर इससे आपके खेल में मदद मिली, तो आप मुझे कॉफ़ी दे सकते हैं।",
    "ar": "إذا ساعدك في مغامرتك، يمكنك أن تدعوني إلى قهوة.",
    "bn": "খেলায় কাজে লাগলে আমাকে এক কাপ কফি কিনে দিতে পারেন।",
    "ru": "Если проект помог вам в игре, можете угостить меня кофе.",
    "ja": "冒険に役立ったら、コーヒーをご馳走していただけます。",
    "id": "Jika membantu petualanganmu, kamu bisa mentraktirku kopi."
  },
  "Reset progress?": {
    "en": "Reset progress?",
    "cs": "Resetovat postup?",
    "de": "Fortschritt zurücksetzen?",
    "es": "¿Restablecer progreso?",
    "fr": "Réinitialiser la progression ?",
    "pt": "Redefinir progresso?",
    "zh": "重置进度？",
    "hi": "प्रगति रीसेट करें?",
    "ar": "إعادة ضبط التقدم؟",
    "bn": "অগ্রগতি রিসেট করবেন?",
    "ru": "Сбросить прогресс?",
    "ja": "進行状況をリセットしますか？",
    "id": "Atur ulang kemajuan?"
  },
  "Import progress?": {
    "en": "Import progress?",
    "cs": "Importovat postup?",
    "de": "Fortschritt importieren?",
    "es": "¿Importar progreso?",
    "fr": "Importer la progression ?",
    "pt": "Importar progresso?",
    "zh": "导入进度？",
    "hi": "प्रगति आयात करें?",
    "ar": "استيراد التقدم؟",
    "bn": "অগ্রগতি আমদানি করবেন?",
    "ru": "Импортировать прогресс?",
    "ja": "進行状況をインポートしますか？",
    "id": "Impor kemajuan?"
  },
  "Copy this URL to transfer your progress to another device.": {
    "en": "Copy this URL to transfer your progress to another device.",
    "cs": "Zkopíruj tuto URL pro přenos postupu na jiné zařízení.",
    "de": "Kopiere diese URL, um deinen Fortschritt auf ein anderes Gerät zu übertragen.",
    "es": "Copia esta URL para transferir tu progreso a otro dispositivo.",
    "fr": "Copiez cette URL pour transférer votre progression vers un autre appareil.",
    "pt": "Copie esta URL para transferir seu progresso para outro dispositivo.",
    "zh": "复制此链接以将进度转移到另一台设备。",
    "hi": "अपनी प्रगति दूसरे उपकरण पर ले जाने के लिए यह URL कॉपी करें।",
    "ar": "انسخ هذا الرابط لنقل تقدمك إلى جهاز آخر.",
    "bn": "অন্য ডিভাইসে অগ্রগতি নিতে এই URL কপি করুন।",
    "ru": "Скопируйте эту ссылку для переноса прогресса на другое устройство.",
    "ja": "このURLをコピーして別の端末に進行状況を転送できます。",
    "id": "Salin URL ini untuk memindahkan kemajuanmu ke perangkat lain."
  },
  "This clears your checklist and manually revealed biomes.": {
    "en": "This clears your checklist and manually revealed biomes.",
    "cs": "Tím se smaže tvůj checklist i ručně odhalené biomy.",
    "de": "Dies löscht deine Checkliste und manuell aufgedeckten Biome.",
    "es": "Esto borra tu lista y los biomas revelados manualmente.",
    "fr": "Cela efface votre liste et les biomes révélés manuellement.",
    "pt": "Isso apaga sua lista e os biomas revelados manualmente.",
    "zh": "这将清除你的清单和手动揭示的生物群系。",
    "hi": "इससे आपकी सूची और हाथ से प्रकट किए गए बायोम मिट जाएंगे।",
    "ar": "سيؤدي هذا إلى مسح قائمتك والمناطق التي كشفتها يدويًا.",
    "bn": "এতে আপনার তালিকা ও নিজে উন্মোচিত বায়োম মুছে যাবে।",
    "ru": "Это удалит ваш список и биомы, открытые вручную.",
    "ja": "チェックリストと手動で公開したバイオームを消去します。",
    "id": "Ini menghapus daftar periksa dan bioma yang diungkap secara manual."
  },
  "This replaces your current checklist with the progress from this URL.": {
    "en": "This replaces your current checklist with the progress from this URL.",
    "cs": "Tím se tvůj současný checklist nahradí postupem z této URL.",
    "de": "Dies ersetzt deine aktuelle Checkliste durch den Fortschritt aus dieser URL.",
    "es": "Esto reemplaza tu lista actual por el progreso de esta URL.",
    "fr": "Cela remplace votre liste actuelle par la progression de cette URL.",
    "pt": "Isso substitui sua lista atual pelo progresso desta URL.",
    "zh": "这将用此链接中的进度替换你当前的清单。",
    "hi": "यह आपकी मौजूदा सूची को इस URL की प्रगति से बदल देगा।",
    "ar": "سيؤدي هذا إلى استبدال قائمتك الحالية بالتقدم الموجود في هذا الرابط.",
    "bn": "এটি আপনার বর্তমান তালিকাকে এই URL-এর অগ্রগতি দিয়ে প্রতিস্থাপন করবে।",
    "ru": "Это заменит ваш текущий список прогрессом из этой ссылки.",
    "ja": "現在のチェックリストをこのURLの進行状況で置き換えます。",
    "id": "Ini mengganti daftar periksamu saat ini dengan kemajuan dari URL ini."
  },
  "Done": {
    "en": "Done",
    "cs": "Hotovo",
    "de": "Fertig",
    "es": "Listo",
    "fr": "Terminé",
    "pt": "Concluído",
    "zh": "完成",
    "hi": "पूर्ण",
    "ar": "تم",
    "bn": "সম্পন্ন",
    "ru": "Готово",
    "ja": "完了",
    "id": "Selesai"
  },
  "Import": {
    "en": "Import",
    "cs": "Importovat",
    "de": "Importieren",
    "es": "Importar",
    "fr": "Importer",
    "pt": "Importar",
    "zh": "导入",
    "hi": "आयात करें",
    "ar": "استيراد",
    "bn": "আমদানি করুন",
    "ru": "Импортировать",
    "ja": "インポート",
    "id": "Impor"
  },
  "Progress reset.": {
    "en": "Progress reset.",
    "cs": "Postup resetován.",
    "de": "Fortschritt zurückgesetzt.",
    "es": "Progreso restablecido.",
    "fr": "Progression réinitialisée.",
    "pt": "Progresso redefinido.",
    "zh": "进度已重置。",
    "hi": "प्रगति रीसेट हुई।",
    "ar": "تمت إعادة ضبط التقدم.",
    "bn": "অগ্রগতি রিসেট হয়েছে।",
    "ru": "Прогресс сброшен.",
    "ja": "進行状況をリセットしました。",
    "id": "Kemajuan diatur ulang."
  },
  "Progress imported.": {
    "en": "Progress imported.",
    "cs": "Postup importován.",
    "de": "Fortschritt importiert.",
    "es": "Progreso importado.",
    "fr": "Progression importée.",
    "pt": "Progresso importado.",
    "zh": "进度已导入。",
    "hi": "प्रगति आयात हुई।",
    "ar": "تم استيراد التقدم.",
    "bn": "অগ্রগতি আমদানি হয়েছে।",
    "ru": "Прогресс импортирован.",
    "ja": "進行状況をインポートしました。",
    "id": "Kemajuan diimpor."
  },
  "Invalid progress URL.": {
    "en": "Invalid progress URL.",
    "cs": "Neplatná URL postupu.",
    "de": "Ungültige Fortschritts-URL.",
    "es": "URL de progreso inválida.",
    "fr": "URL de progression invalide.",
    "pt": "URL de progresso inválida.",
    "zh": "进度链接无效。",
    "hi": "प्रगति का URL अमान्य है।",
    "ar": "رابط التقدم غير صالح.",
    "bn": "অগ্রগতির URL অবৈধ।",
    "ru": "Неверная ссылка на прогресс.",
    "ja": "無効な進行状況のURLです。",
    "id": "URL kemajuan tidak valid."
  },
  "Progress URL copied.": {
    "en": "Progress URL copied.",
    "cs": "URL postupu zkopírována.",
    "de": "Fortschritts-URL kopiert.",
    "es": "URL del progreso copiada.",
    "fr": "URL de progression copiée.",
    "pt": "URL do progresso copiada.",
    "zh": "进度链接已复制。",
    "hi": "प्रगति का URL कॉपी हुआ।",
    "ar": "تم نسخ رابط التقدم.",
    "bn": "অগ্রগতির URL কপি হয়েছে।",
    "ru": "Ссылка на прогресс скопирована.",
    "ja": "進行状況のURLをコピーしました。",
    "id": "URL kemajuan disalin."
  },
  "Miniboss": {
    "en": "Miniboss",
    "cs": "Miniboss",
    "de": "Miniboss",
    "es": "Minijefe",
    "fr": "Mini-boss",
    "pt": "Minichefe",
    "zh": "小首领",
    "hi": "मिनी बॉस",
    "ar": "زعيم صغير",
    "bn": "মিনি বস",
    "ru": "Мини-босс",
    "ja": "ミニボス",
    "id": "Bos mini"
  },
  "Summon: {items}": {
    "en": "Summon: {items}",
    "cs": "Vyvolání: {items}",
    "de": "Beschwörung: {items}",
    "es": "Invocación: {items}",
    "fr": "Invocation : {items}",
    "pt": "Invocação: {items}",
    "zh": "召唤：{items}",
    "hi": "आह्वान: {items}",
    "ar": "الاستدعاء: {items}",
    "bn": "আহ্বান: {items}",
    "ru": "Призыв: {items}",
    "ja": "召喚：{items}",
    "id": "Pemanggilan: {items}"
  },
  "Defeated": {
    "en": "Defeated",
    "cs": "Poražen",
    "de": "Besiegt",
    "es": "Derrotado",
    "fr": "Vaincu",
    "pt": "Derrotado",
    "zh": "已击败",
    "hi": "पराजित",
    "ar": "مهزوم",
    "bn": "পরাজিত",
    "ru": "Побеждён",
    "ja": "討伐済み",
    "id": "Dikalahkan"
  },
  "Open full tracker →": {
    "en": "Open full tracker →",
    "cs": "Otevřít celý tracker →",
    "de": "Vollständigen Tracker öffnen →",
    "es": "Abrir el tracker completo →",
    "fr": "Ouvrir le tracker complet →",
    "pt": "Abrir o tracker completo →",
    "zh": "打开完整追踪器 →",
    "hi": "पूरा ट्रैकर खोलें →",
    "ar": "فتح المتتبّع الكامل →",
    "bn": "সম্পূর্ণ ট্র্যাকার খুলুন →",
    "ru": "Открыть полный трекер →",
    "ja": "トラッカー全体を開く →",
    "id": "Buka tracker lengkap →"
  },
  "Close progress": {
    "en": "Close Progress",
    "cs": "Zavřít Progress",
    "de": "Progress schließen",
    "es": "Cerrar Progress",
    "fr": "Fermer Progress",
    "pt": "Fechar Progress",
    "zh": "关闭 Progress",
    "hi": "Progress बंद करें",
    "ar": "إغلاق Progress",
    "bn": "Progress বন্ধ করুন",
    "ru": "Закрыть Progress",
    "ja": "Progress を閉じる",
    "id": "Tutup Progress"
  },
  "Loading progress…": {
    "en": "Loading progress…",
    "cs": "Načítání postupu…",
    "de": "Fortschritt wird geladen…",
    "es": "Cargando progreso…",
    "fr": "Chargement de la progression…",
    "pt": "Carregando progresso…",
    "zh": "正在加载进度…",
    "hi": "प्रगति लोड हो रही है…",
    "ar": "جارٍ تحميل التقدم…",
    "bn": "অগ্রগতি লোড হচ্ছে…",
    "ru": "Загрузка прогресса…",
    "ja": "進捗を読み込み中…",
    "id": "Memuat progres…"
  },
  "Could not load progress.": {
    "en": "Could not load progress.",
    "cs": "Postup se nepodařilo načíst.",
    "de": "Fortschritt konnte nicht geladen werden.",
    "es": "No se pudo cargar el progreso.",
    "fr": "Impossible de charger la progression.",
    "pt": "Não foi possível carregar o progresso.",
    "zh": "无法加载进度。",
    "hi": "प्रगति लोड नहीं हो सकी।",
    "ar": "تعذّر تحميل التقدم.",
    "bn": "অগ্রগতি লোড করা যায়নি।",
    "ru": "Не удалось загрузить прогресс.",
    "ja": "進捗を読み込めませんでした。",
    "id": "Tidak dapat memuat progres."
  },
  "Retry": {
    "en": "Retry",
    "cs": "Zkusit znovu",
    "de": "Erneut versuchen",
    "es": "Reintentar",
    "fr": "Réessayer",
    "pt": "Tentar novamente",
    "zh": "重试",
    "hi": "फिर कोशिश करें",
    "ar": "إعادة المحاولة",
    "bn": "আবার চেষ্টা করুন",
    "ru": "Повторить",
    "ja": "再試行",
    "id": "Coba lagi"
  },
  "Not defeated": {
    "en": "Not defeated",
    "cs": "Neporažen",
    "de": "Nicht besiegt",
    "es": "Sin derrotar",
    "fr": "Non vaincu",
    "pt": "Não derrotado",
    "zh": "未击败",
    "hi": "पराजित नहीं",
    "ar": "لم يُهزم",
    "bn": "পরাজিত নয়",
    "ru": "Не побеждён",
    "ja": "未討伐",
    "id": "Belum dikalahkan"
  },
  "Next up": {
    "en": "Next up",
    "cs": "Další na řadě",
    "de": "Als Nächstes",
    "es": "A continuación",
    "fr": "À suivre",
    "pt": "A seguir",
    "zh": "下一个目标",
    "hi": "अगला लक्ष्य",
    "ar": "التالي",
    "bn": "পরবর্তী লক্ষ্য",
    "ru": "Следующая цель",
    "ja": "次の目標",
    "id": "Berikutnya"
  },
  "Your journey": {
    "en": "Your journey",
    "cs": "Tvá cesta",
    "de": "Deine Reise",
    "es": "Tu viaje",
    "fr": "Votre voyage",
    "pt": "Sua jornada",
    "zh": "你的旅程",
    "hi": "आपकी यात्रा",
    "ar": "رحلتك",
    "bn": "তোমার যাত্রা",
    "ru": "Твой путь",
    "ja": "あなたの旅",
    "id": "Perjalananmu"
  },
  "You've reached: {biome}": {
    "en": "You've reached: {biome}",
    "cs": "Došel jsi do: {biome}",
    "de": "Du hast erreicht: {biome}",
    "es": "Has llegado a: {biome}",
    "fr": "Vous avez atteint : {biome}",
    "pt": "Você chegou a: {biome}",
    "zh": "已到达：{biome}",
    "hi": "आप यहाँ पहुँचे हैं: {biome}",
    "ar": "لقد وصلت إلى: {biome}",
    "bn": "তুমি পৌঁছেছ: {biome}",
    "ru": "Ты достиг: {biome}",
    "ja": "到達地点：{biome}",
    "id": "Kamu telah mencapai: {biome}"
  },
  "Unmark bosses to go back": {
    "en": "Unmark bosses to go back",
    "cs": "Pro návrat zruš označení poražených bossů",
    "de": "Entferne besiegte Bosse, um zurückzugehen",
    "es": "Desmarca los jefes para retroceder",
    "fr": "Décochez les boss pour revenir en arrière",
    "pt": "Desmarque os chefes para voltar",
    "zh": "取消标记首领以返回",
    "hi": "पीछे जाने के लिए बॉस का निशान हटाएँ",
    "ar": "ألغِ تحديد الزعماء للعودة",
    "bn": "পিছনে যেতে বসের চিহ্ন সরাও",
    "ru": "Сними отметки с боссов, чтобы вернуться",
    "ja": "戻るにはボスの討伐マークを外してください",
    "id": "Hapus tanda bos untuk kembali"
  },
  "Travel on — move the slider when you reach the next biome.": {
    "en": "Travel on — move the slider when you reach the next biome.",
    "cs": "Pokračuj v cestě — až dorazíš do dalšího biomu, posuň jezdec.",
    "de": "Reise weiter — verschiebe den Regler, sobald du das nächste Biom erreichst.",
    "es": "Sigue viajando: mueve el control al llegar al siguiente bioma.",
    "fr": "Poursuivez le voyage — déplacez le curseur en atteignant le prochain biome.",
    "pt": "Continue a viagem — mova o controle ao chegar ao próximo bioma.",
    "zh": "继续旅行——到达下一个生物群系时移动滑块。",
    "hi": "यात्रा जारी रखें — अगले बायोम तक पहुँचने पर स्लाइडर खिसकाएँ।",
    "ar": "واصل رحلتك — حرّك المؤشر عند الوصول إلى المنطقة التالية.",
    "bn": "যাত্রা চালিয়ে যাও — পরের বায়োমে পৌঁছে স্লাইডার সরাও।",
    "ru": "Продолжай путь — передвинь ползунок, когда достигнешь следующего биома.",
    "ja": "旅を続けよう。次のバイオームに到達したらスライダーを動かしてください。",
    "id": "Lanjutkan perjalanan — geser pengatur saat mencapai bioma berikutnya."
  },
  "Saga complete": {
    "en": "Saga complete",
    "cs": "Sága dokončena",
    "de": "Saga abgeschlossen",
    "es": "Saga completada",
    "fr": "Saga achevée",
    "pt": "Saga concluída",
    "zh": "传奇已完成",
    "hi": "गाथा पूरी हुई",
    "ar": "اكتملت الملحمة",
    "bn": "গাথা সম্পূর্ণ",
    "ru": "Сага завершена",
    "ja": "サーガ完了",
    "id": "Saga selesai"
  },
  "Biome {count}": {
    "en": {
      "one": "Biome {count}",
      "other": "Biome {count}"
    },
    "cs": {
      "one": "Biom {count}",
      "few": "Biom {count}",
      "many": "Biom {count}",
      "other": "Biom {count}"
    },
    "de": {
      "one": "Biom {count}",
      "other": "Biom {count}"
    },
    "es": {
      "one": "Bioma {count}",
      "many": "Bioma {count}",
      "other": "Bioma {count}"
    },
    "fr": {
      "one": "Biome {count}",
      "many": "Biome {count}",
      "other": "Biome {count}"
    },
    "pt": {
      "one": "Bioma {count}",
      "many": "Bioma {count}",
      "other": "Bioma {count}"
    },
    "zh": {
      "other": "生物群系 {count}"
    },
    "hi": {
      "one": "बायोम {count}",
      "other": "बायोम {count}"
    },
    "ar": {
      "zero": "المنطقة {count}",
      "one": "المنطقة {count}",
      "two": "المنطقة {count}",
      "few": "المنطقة {count}",
      "many": "المنطقة {count}",
      "other": "المنطقة {count}"
    },
    "bn": {
      "one": "বায়োম {count}",
      "other": "বায়োম {count}"
    },
    "ru": {
      "one": "Биом {count}",
      "few": "Биом {count}",
      "many": "Биом {count}",
      "other": "Биом {count}"
    },
    "ja": {
      "other": "バイオーム {count}"
    },
    "id": {
      "other": "Bioma {count}"
    }
  },
  "Biome {count} of {total}": {
    "en": {
      "one": "Biome {count} of {total}",
      "other": "Biome {count} of {total}"
    },
    "cs": {
      "one": "Biom {count} z {total}",
      "few": "Biom {count} z {total}",
      "many": "Biom {count} z {total}",
      "other": "Biom {count} z {total}"
    },
    "de": {
      "one": "Biom {count} von {total}",
      "other": "Biom {count} von {total}"
    },
    "es": {
      "one": "Bioma {count} de {total}",
      "many": "Bioma {count} de {total}",
      "other": "Bioma {count} de {total}"
    },
    "fr": {
      "one": "Biome {count} sur {total}",
      "many": "Biome {count} sur {total}",
      "other": "Biome {count} sur {total}"
    },
    "pt": {
      "one": "Bioma {count} de {total}",
      "many": "Bioma {count} de {total}",
      "other": "Bioma {count} de {total}"
    },
    "zh": {
      "other": "生物群系 {count} / {total}"
    },
    "hi": {
      "one": "बायोम {count} / {total}",
      "other": "बायोम {count} / {total}"
    },
    "ar": {
      "zero": "المنطقة {count} من {total}",
      "one": "المنطقة {count} من {total}",
      "two": "المنطقة {count} من {total}",
      "few": "المنطقة {count} من {total}",
      "many": "المنطقة {count} من {total}",
      "other": "المنطقة {count} من {total}"
    },
    "bn": {
      "one": "বায়োম {count} / {total}",
      "other": "বায়োম {count} / {total}"
    },
    "ru": {
      "one": "Биом {count} из {total}",
      "few": "Биом {count} из {total}",
      "many": "Биом {count} из {total}",
      "other": "Биом {count} из {total}"
    },
    "ja": {
      "other": "バイオーム {count} / {total}"
    },
    "id": {
      "other": "Bioma {count} dari {total}"
    }
  },
  "Biome {count} of {total}: {biome}": {
    "en": {
      "one": "Biome {count} of {total}: {biome}",
      "other": "Biome {count} of {total}: {biome}"
    },
    "cs": {
      "one": "Biom {count} z {total}: {biome}",
      "few": "Biom {count} z {total}: {biome}",
      "many": "Biom {count} z {total}: {biome}",
      "other": "Biom {count} z {total}: {biome}"
    },
    "de": {
      "one": "Biom {count} von {total}: {biome}",
      "other": "Biom {count} von {total}: {biome}"
    },
    "es": {
      "one": "Bioma {count} de {total}: {biome}",
      "many": "Bioma {count} de {total}: {biome}",
      "other": "Bioma {count} de {total}: {biome}"
    },
    "fr": {
      "one": "Biome {count} sur {total} : {biome}",
      "many": "Biome {count} sur {total} : {biome}",
      "other": "Biome {count} sur {total} : {biome}"
    },
    "pt": {
      "one": "Bioma {count} de {total}: {biome}",
      "many": "Bioma {count} de {total}: {biome}",
      "other": "Bioma {count} de {total}: {biome}"
    },
    "zh": {
      "other": "生物群系 {count} / {total}：{biome}"
    },
    "hi": {
      "one": "बायोम {count} / {total}: {biome}",
      "other": "बायोम {count} / {total}: {biome}"
    },
    "ar": {
      "zero": "المنطقة {count} من {total}: {biome}",
      "one": "المنطقة {count} من {total}: {biome}",
      "two": "المنطقة {count} من {total}: {biome}",
      "few": "المنطقة {count} من {total}: {biome}",
      "many": "المنطقة {count} من {total}: {biome}",
      "other": "المنطقة {count} من {total}: {biome}"
    },
    "bn": {
      "one": "বায়োম {count} / {total}: {biome}",
      "other": "বায়োম {count} / {total}: {biome}"
    },
    "ru": {
      "one": "Биом {count} из {total}: {biome}",
      "few": "Биом {count} из {total}: {biome}",
      "many": "Биом {count} из {total}: {biome}",
      "other": "Биом {count} из {total}: {biome}"
    },
    "ja": {
      "other": "バイオーム {count} / {total}：{biome}"
    },
    "id": {
      "other": "Bioma {count} dari {total}: {biome}"
    }
  },
  "{count} of {total} bosses": {
    "en": {
      "one": "{count} of {total} bosses",
      "other": "{count} of {total} bosses"
    },
    "cs": {
      "one": "{count} z {total} bossů",
      "few": "{count} z {total} bossů",
      "many": "{count} z {total} bossů",
      "other": "{count} z {total} bossů"
    },
    "de": {
      "one": "{count} von {total} Bossen",
      "other": "{count} von {total} Bossen"
    },
    "es": {
      "one": "{count} de {total} jefes",
      "many": "{count} de {total} jefes",
      "other": "{count} de {total} jefes"
    },
    "fr": {
      "one": "{count} boss sur {total}",
      "many": "{count} boss sur {total}",
      "other": "{count} boss sur {total}"
    },
    "pt": {
      "one": "{count} de {total} chefes",
      "many": "{count} de {total} chefes",
      "other": "{count} de {total} chefes"
    },
    "zh": {
      "other": "首领 {count} / {total}"
    },
    "hi": {
      "one": "बॉस {count} / {total}",
      "other": "बॉस {count} / {total}"
    },
    "ar": {
      "zero": "الزعماء {count} من {total}",
      "one": "الزعماء {count} من {total}",
      "two": "الزعماء {count} من {total}",
      "few": "الزعماء {count} من {total}",
      "many": "الزعماء {count} من {total}",
      "other": "الزعماء {count} من {total}"
    },
    "bn": {
      "one": "বস {count} / {total}",
      "other": "বস {count} / {total}"
    },
    "ru": {
      "one": "Боссы: {count} из {total}",
      "few": "Боссы: {count} из {total}",
      "many": "Боссы: {count} из {total}",
      "other": "Боссы: {count} из {total}"
    },
    "ja": {
      "other": "ボス {count} / {total}"
    },
    "id": {
      "other": "{count} dari {total} bos"
    }
  },
  "{count} of {total} minibosses": {
    "en": {
      "one": "{count} of {total} minibosses",
      "other": "{count} of {total} minibosses"
    },
    "cs": {
      "one": "{count} z {total} minibossů",
      "few": "{count} z {total} minibossů",
      "many": "{count} z {total} minibossů",
      "other": "{count} z {total} minibossů"
    },
    "de": {
      "one": "{count} von {total} Minibossen",
      "other": "{count} von {total} Minibossen"
    },
    "es": {
      "one": "{count} de {total} minijefes",
      "many": "{count} de {total} minijefes",
      "other": "{count} de {total} minijefes"
    },
    "fr": {
      "one": "{count} mini-boss sur {total}",
      "many": "{count} mini-boss sur {total}",
      "other": "{count} mini-boss sur {total}"
    },
    "pt": {
      "one": "{count} de {total} minichefes",
      "many": "{count} de {total} minichefes",
      "other": "{count} de {total} minichefes"
    },
    "zh": {
      "other": "小首领 {count} / {total}"
    },
    "hi": {
      "one": "मिनीबॉस {count} / {total}",
      "other": "मिनीबॉस {count} / {total}"
    },
    "ar": {
      "zero": "الزعماء الصغار {count} من {total}",
      "one": "الزعماء الصغار {count} من {total}",
      "two": "الزعماء الصغار {count} من {total}",
      "few": "الزعماء الصغار {count} من {total}",
      "many": "الزعماء الصغار {count} من {total}",
      "other": "الزعماء الصغار {count} من {total}"
    },
    "bn": {
      "one": "মিনিবস {count} / {total}",
      "other": "মিনিবস {count} / {total}"
    },
    "ru": {
      "one": "Мини-боссы: {count} из {total}",
      "few": "Мини-боссы: {count} из {total}",
      "many": "Мини-боссы: {count} из {total}",
      "other": "Мини-боссы: {count} из {total}"
    },
    "ja": {
      "other": "ミニボス {count} / {total}"
    },
    "id": {
      "other": "{count} dari {total} bos mini"
    }
  },
  "⛓ Progress {count}/{total}": {
    "en": {
      "one": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "cs": {
      "one": "⛓ Progress {count}/{total}",
      "few": "⛓ Progress {count}/{total}",
      "many": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "de": {
      "one": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "es": {
      "one": "⛓ Progress {count}/{total}",
      "many": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "fr": {
      "one": "⛓ Progress {count}/{total}",
      "many": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "pt": {
      "one": "⛓ Progress {count}/{total}",
      "many": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "zh": {
      "other": "⛓ Progress {count}/{total}"
    },
    "hi": {
      "one": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "ar": {
      "zero": "⛓ Progress {count}/{total}",
      "one": "⛓ Progress {count}/{total}",
      "two": "⛓ Progress {count}/{total}",
      "few": "⛓ Progress {count}/{total}",
      "many": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "bn": {
      "one": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "ru": {
      "one": "⛓ Progress {count}/{total}",
      "few": "⛓ Progress {count}/{total}",
      "many": "⛓ Progress {count}/{total}",
      "other": "⛓ Progress {count}/{total}"
    },
    "ja": {
      "other": "⛓ Progress {count}/{total}"
    },
    "id": {
      "other": "⛓ Progress {count}/{total}"
    }
  },
  "Move the slider as you explore. Select a portrait to mark a victory.": {
    "en": "Move the slider as you explore. Select a portrait to mark a victory.",
    "cs": "Posouvej jezdec, jak objevuješ svět. Kliknutím na portrét označ vítězství.",
    "de": "Bewege den Regler beim Erkunden. Wähle ein Porträt, um einen Sieg zu markieren.",
    "es": "Mueve el control al explorar. Selecciona un retrato para marcar una victoria.",
    "fr": "Déplacez le curseur au fil de vos découvertes. Sélectionnez un portrait pour marquer une victoire.",
    "pt": "Mova o controle conforme explora. Selecione um retrato para marcar uma vitória.",
    "zh": "探索时移动滑块。点击头像标记胜利。",
    "hi": "खोज करते हुए स्लाइडर खिसकाएँ। जीत दर्ज करने के लिए चित्र चुनें।",
    "ar": "حرّك المؤشر أثناء الاستكشاف. اختر صورة لتسجيل انتصار.",
    "bn": "অন্বেষণের সাথে স্লাইডার সরাও। জয় চিহ্নিত করতে প্রতিকৃতি বেছে নাও।",
    "ru": "Передвигай ползунок по мере исследования мира. Нажми на портрет, чтобы отметить победу.",
    "ja": "探索に合わせてスライダーを動かしましょう。ポートレートを選ぶと勝利を記録できます。",
    "id": "Geser pengatur saat menjelajah. Pilih potret untuk menandai kemenangan."
  }
};
