// Generated by scripts/build-i18n.mjs — DO NOT EDIT MANUALLY
globalThis.VC_MESSAGES = {
  "Navigation": {
    "en": "Navigation",
    "cs": "Navigace",
    "de": "Navigation",
    "es": "Navegación",
    "fr": "Navigation",
    "pt": "Navegação",
    "zh": "导航",
    "hi": "नेविगेशन",
    "ar": "التنقل",
    "bn": "নেভিগেশন",
    "ru": "Навигация",
    "ja": "ナビゲーション",
    "id": "Navigasi"
  },
  "← Valheim Companion": {
    "en": "← Valheim Companion",
    "cs": "← Valheim Companion",
    "de": "← Valheim Companion",
    "es": "← Valheim Companion",
    "fr": "← Valheim Companion",
    "pt": "← Valheim Companion",
    "zh": "← Valheim Companion",
    "hi": "← Valheim Companion",
    "ar": "← Valheim Companion",
    "bn": "← Valheim Companion",
    "ru": "← Valheim Companion",
    "ja": "← Valheim Companion",
    "id": "← Valheim Companion"
  },
  "Language": {
    "en": "Language",
    "cs": "Jazyk",
    "de": "Sprache",
    "es": "Idioma",
    "fr": "Langue",
    "pt": "Idioma",
    "zh": "语言",
    "hi": "भाषा",
    "ar": "اللغة",
    "bn": "ভাষা",
    "ru": "Язык",
    "ja": "言語",
    "id": "Bahasa"
  },
  "Auto (browser)": {
    "en": "Auto (browser)",
    "cs": "Automaticky (prohlížeč)",
    "de": "Automatisch (Browser)",
    "es": "Automático (navegador)",
    "fr": "Auto (navigateur)",
    "pt": "Automático (navegador)",
    "zh": "自动（浏览器）",
    "hi": "स्वचालित (ब्राउज़र)",
    "ar": "تلقائي (المتصفح)",
    "bn": "স্বয়ংক্রিয় (ব্রাউজার)",
    "ru": "Авто (браузер)",
    "ja": "自動（ブラウザー）",
    "id": "Otomatis (browser)"
  },
  "Fan project, not affiliated with Iron Gate.": {
    "en": "Fan project, not affiliated with Iron Gate.",
    "cs": "Fanouškovský projekt bez spojení s Iron Gate.",
    "de": "Fanprojekt, nicht mit Iron Gate verbunden.",
    "es": "Proyecto de fans, sin afiliación con Iron Gate.",
    "fr": "Projet de fans, sans affiliation avec Iron Gate.",
    "pt": "Projeto de fãs, sem vínculo com a Iron Gate.",
    "zh": "粉丝项目，与 Iron Gate 无关联。",
    "hi": "प्रशंसक परियोजना, Iron Gate से संबद्ध नहीं।",
    "ar": "مشروع معجبين، غير تابع لـ Iron Gate.",
    "bn": "ভক্তদের প্রকল্প, Iron Gate-এর সঙ্গে সম্পর্কিত নয়।",
    "ru": "Фанатский проект, не связан с Iron Gate.",
    "ja": "ファンによるプロジェクト。Iron Gate とは関係ありません。",
    "id": "Proyek penggemar, tidak berafiliasi dengan Iron Gate."
  },
  "Free, ad-free and made in my spare time.": {
    "en": "Free, ad-free and made in my spare time.",
    "cs": "Zdarma, bez reklam a vytvořeno ve volném čase.",
    "de": "Kostenlos, werbefrei und in meiner Freizeit erstellt.",
    "es": "Gratis, sin publicidad y hecho en mi tiempo libre.",
    "fr": "Gratuit, sans publicité et créé sur mon temps libre.",
    "pt": "Gratuito, sem anúncios e feito no meu tempo livre.",
    "zh": "免费无广告，利用业余时间开发。",
    "hi": "निःशुल्क, विज्ञापन-मुक्त और मेरे खाली समय में निर्मित।",
    "ar": "مجاني وبدون إعلانات ومصنوع في وقت فراغي.",
    "bn": "সম্পূর্ণ বিনামূল্যে, বিজ্ঞাপনহীন এবং অবসরে তৈরি।",
    "ru": "Бесплатно, без рекламы и создано в свободное время.",
    "ja": "完全無料・広告なし・個人の趣味で制作。",
    "id": "Gratis, bebas iklan, dan dibuat di waktu luang saya."
  },
  "Buy Me a Coffee at ko-fi.com": {
    "en": "Buy Me a Coffee at ko-fi.com",
    "cs": "Koupit mi kávu na ko-fi.com",
    "de": "Kauf mir einen Kaffee auf ko-fi.com",
    "es": "Invítame a un café en ko-fi.com",
    "fr": "Offrez-moi un café sur ko-fi.com",
    "pt": "Pague-me um café no ko-fi.com",
    "zh": "在 ko-fi.com 上请我喝杯咖啡",
    "hi": "ko-fi.com पर मुझे कॉफ़ी पिलाएँ",
    "ar": "اشترِ لي قهوة عبر ko-fi.com",
    "bn": "ko-fi.com-এ আমাকে একটি কফি দিন",
    "ru": "Купить мне кофе на ko-fi.com",
    "ja": "ko-fi.com でコーヒーを支援する",
    "id": "Beli saya kopi di ko-fi.com"
  },
  "Cancel": {
    "en": "Cancel",
    "cs": "Zrušit",
    "de": "Abbrechen",
    "es": "Cancelar",
    "fr": "Annuler",
    "pt": "Cancelar",
    "zh": "取消",
    "hi": "रद्द करें",
    "ar": "إلغاء",
    "bn": "বাতিল",
    "ru": "Отмена",
    "ja": "キャンセル",
    "id": "Batal"
  },
  "Reveal": {
    "en": "Reveal",
    "cs": "Odhalit",
    "de": "Enthüllen",
    "es": "Revelar",
    "fr": "Révéler",
    "pt": "Revelar",
    "zh": "揭示",
    "hi": "दिखाएँ",
    "ar": "كشف",
    "bn": "প্রকাশ করুন",
    "ru": "Показать",
    "ja": "表示",
    "id": "Ungkap"
  },
  "Visited": {
    "en": "Visited",
    "cs": "Navštíveno",
    "de": "Besucht",
    "es": "Visitado",
    "fr": "Visité",
    "pt": "Visitado",
    "zh": "已到访",
    "hi": "दौरा किया",
    "ar": "تمت الزيارة",
    "bn": "পরিদর্শিত",
    "ru": "Посещено",
    "ja": "訪問済み",
    "id": "Dikunjungi"
  },
  "Defeated": {
    "en": "Defeated",
    "cs": "Poražen",
    "de": "Besiegt",
    "es": "Derrotado",
    "fr": "Vaincu",
    "pt": "Derrotado",
    "zh": "已击败",
    "hi": "पराजित",
    "ar": "مهزوم",
    "bn": "পরাজিত",
    "ru": "Побеждён",
    "ja": "討伐済み",
    "id": "Dikalahkan"
  },
  "Boss": {
    "en": "Boss",
    "cs": "Boss",
    "de": "Boss",
    "es": "Jefe",
    "fr": "Boss",
    "pt": "Chefe",
    "zh": "首领",
    "hi": "बॉस",
    "ar": "زعيم",
    "bn": "বস",
    "ru": "Босс",
    "ja": "ボス",
    "id": "Bos"
  },
  "Miniboss": {
    "en": "Miniboss",
    "cs": "Miniboss",
    "de": "Miniboss",
    "es": "Minijefe",
    "fr": "Mini-boss",
    "pt": "Minichefe",
    "zh": "小首领",
    "hi": "मिनी बॉस",
    "ar": "زعيم صغير",
    "bn": "মিনি বস",
    "ru": "Мини-босс",
    "ja": "ミニボス",
    "id": "Bos mini"
  },
  "Data:": {
    "en": "Data:",
    "cs": "Data:",
    "de": "Daten:",
    "es": "Datos:",
    "fr": "Données :",
    "pt": "Dados:",
    "zh": "数据：",
    "hi": "डेटा:",
    "ar": "البيانات:",
    "bn": "তথ্য:",
    "ru": "Данные:",
    "ja": "データ：",
    "id": "Data:"
  },
  "Your journey through Valheim, one discovery at a time.": {
    "en": "Your journey through Valheim, one discovery at a time.",
    "cs": "Tvá cesta Valheimem, jeden objev za druhým.",
    "de": "Deine Reise durch Valheim, eine Entdeckung nach der anderen.",
    "es": "Tu viaje por Valheim, un descubrimiento a la vez.",
    "fr": "Votre voyage dans Valheim, une découverte à la fois.",
    "pt": "Sua jornada por Valheim, uma descoberta de cada vez.",
    "zh": "探索英灵神殿，一步一个新发现。",
    "hi": "वाल्हेम में आपकी यात्रा, एक समय में एक नई खोज।",
    "ar": "رحلتك في فالهايم، اكتشافًا تلو الآخر.",
    "bn": "ভালহেইমে আপনার যাত্রা, একবারে একটি নতুন আবিষ্কার।",
    "ru": "Ваш путь по Вальхейму, открытие за открытием.",
    "ja": "Valheimの旅、一つずつ新たな発見を。",
    "id": "Perjalananmu di Valheim, satu penemuan setiap saat."
  },
  "Progress summary": {
    "en": "Progress summary",
    "cs": "Souhrn postupu",
    "de": "Fortschrittsübersicht",
    "es": "Resumen del progreso",
    "fr": "Résumé de la progression",
    "pt": "Resumo do progresso",
    "zh": "进度概览",
    "hi": "प्रगति का सारांश",
    "ar": "ملخص التقدم",
    "bn": "অগ্রগতির সারাংশ",
    "ru": "Обзор прогресса",
    "ja": "進行状況の概要",
    "id": "Ringkasan kemajuan"
  },
  "Biomes revealed": {
    "en": "Biomes revealed",
    "cs": "Odhalené biomy",
    "de": "Aufgedeckte Biome",
    "es": "Biomas revelados",
    "fr": "Biomes révélés",
    "pt": "Biomas revelados",
    "zh": "已揭示的生物群系",
    "hi": "प्रकट हुए बायोम",
    "ar": "المناطق المكشوفة",
    "bn": "উন্মোচিত বায়োম",
    "ru": "Открытые биомы",
    "ja": "公開したバイオーム",
    "id": "Bioma terungkap"
  },
  "Share / transfer progress": {
    "en": "Share / transfer progress",
    "cs": "Sdílet / přenést postup",
    "de": "Fortschritt teilen / übertragen",
    "es": "Compartir / transferir progreso",
    "fr": "Partager / transférer la progression",
    "pt": "Compartilhar / transferir progresso",
    "zh": "分享 / 转移进度",
    "hi": "प्रगति साझा / स्थानांतरित करें",
    "ar": "مشاركة / نقل التقدم",
    "bn": "অগ্রগতি শেয়ার / স্থানান্তর করুন",
    "ru": "Поделиться / перенести прогресс",
    "ja": "進行状況を共有 / 転送",
    "id": "Bagikan / pindahkan kemajuan"
  },
  "Reset progress": {
    "en": "Reset progress",
    "cs": "Resetovat postup",
    "de": "Fortschritt zurücksetzen",
    "es": "Restablecer progreso",
    "fr": "Réinitialiser la progression",
    "pt": "Redefinir progresso",
    "zh": "重置进度",
    "hi": "प्रगति रीसेट करें",
    "ar": "إعادة ضبط التقدم",
    "bn": "অগ্রগতি রিসেট করুন",
    "ru": "Сбросить прогресс",
    "ja": "進行状況をリセット",
    "id": "Atur ulang kemajuan"
  },
  "Progress URL": {
    "en": "Progress URL",
    "cs": "URL postupu",
    "de": "Fortschritts-URL",
    "es": "URL del progreso",
    "fr": "URL de progression",
    "pt": "URL do progresso",
    "zh": "进度链接",
    "hi": "प्रगति का URL",
    "ar": "رابط التقدم",
    "bn": "অগ্রগতির URL",
    "ru": "Ссылка на прогресс",
    "ja": "進行状況のURL",
    "id": "URL kemajuan"
  },
  "If it helped your run, you can buy me a coffee.": {
    "en": "If it helped your run, you can buy me a coffee.",
    "cs": "Pokud ti pomohl při hraní, můžeš mi koupit kávu.",
    "de": "Wenn es dir beim Spielen geholfen hat, kannst du mir einen Kaffee spendieren.",
    "es": "Si te ayudó en tu partida, puedes invitarme a un café.",
    "fr": "Si ce projet vous a aidé, vous pouvez m'offrir un café.",
    "pt": "Se ajudou na sua aventura, você pode me pagar um café.",
    "zh": "如果对你的冒险有帮助，可以请我喝杯咖啡。",
    "hi": "अगर इससे आपके खेल में मदद मिली, तो आप मुझे कॉफ़ी दे सकते हैं।",
    "ar": "إذا ساعدك في مغامرتك، يمكنك أن تدعوني إلى قهوة.",
    "bn": "খেলায় কাজে লাগলে আমাকে এক কাপ কফি কিনে দিতে পারেন।",
    "ru": "Если проект помог вам в игре, можете угостить меня кофе.",
    "ja": "冒険に役立ったら、コーヒーをご馳走していただけます。",
    "id": "Jika membantu petualanganmu, kamu bisa mentraktirku kopi."
  },
  "Summon: {items}": {
    "en": "Summon: {items}",
    "cs": "Vyvolání: {items}",
    "de": "Beschwörung: {items}",
    "es": "Invocación: {items}",
    "fr": "Invocation : {items}",
    "pt": "Invocação: {items}",
    "zh": "召唤：{items}",
    "hi": "आह्वान: {items}",
    "ar": "الاستدعاء: {items}",
    "bn": "আহ্বান: {items}",
    "ru": "Призыв: {items}",
    "ja": "召喚：{items}",
    "id": "Pemanggilan: {items}"
  },
  "Biome {number}": {
    "en": "Biome {number}",
    "cs": "Biom {number}",
    "de": "Biom {number}",
    "es": "Bioma {number}",
    "fr": "Biome {number}",
    "pt": "Bioma {number}",
    "zh": "生物群系 {number}",
    "hi": "बायोम {number}",
    "ar": "المنطقة {number}",
    "bn": "বায়োম {number}",
    "ru": "Биом {number}",
    "ja": "バイオーム {number}",
    "id": "Bioma {number}"
  },
  "Key drops": {
    "en": "Key drops",
    "cs": "Klíčové dropy",
    "de": "Wichtige Beute",
    "es": "Botín clave",
    "fr": "Butin essentiel",
    "pt": "Saques essenciais",
    "zh": "关键掉落",
    "hi": "मुख्य लूट",
    "ar": "الغنائم الأساسية",
    "bn": "গুরুত্বপূর্ণ লুট",
    "ru": "Ключевая добыча",
    "ja": "重要なドロップ",
    "id": "Jarahan penting"
  },
  "Reset progress?": {
    "en": "Reset progress?",
    "cs": "Resetovat postup?",
    "de": "Fortschritt zurücksetzen?",
    "es": "¿Restablecer progreso?",
    "fr": "Réinitialiser la progression ?",
    "pt": "Redefinir progresso?",
    "zh": "重置进度？",
    "hi": "प्रगति रीसेट करें?",
    "ar": "إعادة ضبط التقدم؟",
    "bn": "অগ্রগতি রিসেট করবেন?",
    "ru": "Сбросить прогресс?",
    "ja": "進行状況をリセットしますか？",
    "id": "Atur ulang kemajuan?"
  },
  "Import progress?": {
    "en": "Import progress?",
    "cs": "Importovat postup?",
    "de": "Fortschritt importieren?",
    "es": "¿Importar progreso?",
    "fr": "Importer la progression ?",
    "pt": "Importar progresso?",
    "zh": "导入进度？",
    "hi": "प्रगति आयात करें?",
    "ar": "استيراد التقدم؟",
    "bn": "অগ্রগতি আমদানি করবেন?",
    "ru": "Импортировать прогресс?",
    "ja": "進行状況をインポートしますか？",
    "id": "Impor kemajuan?"
  },
  "Copy this URL to transfer your progress to another device.": {
    "en": "Copy this URL to transfer your progress to another device.",
    "cs": "Zkopíruj tuto URL pro přenos postupu na jiné zařízení.",
    "de": "Kopiere diese URL, um deinen Fortschritt auf ein anderes Gerät zu übertragen.",
    "es": "Copia esta URL para transferir tu progreso a otro dispositivo.",
    "fr": "Copiez cette URL pour transférer votre progression vers un autre appareil.",
    "pt": "Copie esta URL para transferir seu progresso para outro dispositivo.",
    "zh": "复制此链接以将进度转移到另一台设备。",
    "hi": "अपनी प्रगति दूसरे उपकरण पर ले जाने के लिए यह URL कॉपी करें।",
    "ar": "انسخ هذا الرابط لنقل تقدمك إلى جهاز آخر.",
    "bn": "অন্য ডিভাইসে অগ্রগতি নিতে এই URL কপি করুন।",
    "ru": "Скопируйте эту ссылку для переноса прогресса на другое устройство.",
    "ja": "このURLをコピーして別の端末に進行状況を転送できます。",
    "id": "Salin URL ini untuk memindahkan kemajuanmu ke perangkat lain."
  },
  "This clears your checklist and manually revealed biomes.": {
    "en": "This clears your checklist and manually revealed biomes.",
    "cs": "Tím se smaže tvůj checklist i ručně odhalené biomy.",
    "de": "Dies löscht deine Checkliste und manuell aufgedeckten Biome.",
    "es": "Esto borra tu lista y los biomas revelados manualmente.",
    "fr": "Cela efface votre liste et les biomes révélés manuellement.",
    "pt": "Isso apaga sua lista e os biomas revelados manualmente.",
    "zh": "这将清除你的清单和手动揭示的生物群系。",
    "hi": "इससे आपकी सूची और हाथ से प्रकट किए गए बायोम मिट जाएंगे।",
    "ar": "سيؤدي هذا إلى مسح قائمتك والمناطق التي كشفتها يدويًا.",
    "bn": "এতে আপনার তালিকা ও নিজে উন্মোচিত বায়োম মুছে যাবে।",
    "ru": "Это удалит ваш список и биомы, открытые вручную.",
    "ja": "チェックリストと手動で公開したバイオームを消去します。",
    "id": "Ini menghapus daftar periksa dan bioma yang diungkap secara manual."
  },
  "This replaces your current checklist with the progress from this URL.": {
    "en": "This replaces your current checklist with the progress from this URL.",
    "cs": "Tím se tvůj současný checklist nahradí postupem z této URL.",
    "de": "Dies ersetzt deine aktuelle Checkliste durch den Fortschritt aus dieser URL.",
    "es": "Esto reemplaza tu lista actual por el progreso de esta URL.",
    "fr": "Cela remplace votre liste actuelle par la progression de cette URL.",
    "pt": "Isso substitui sua lista atual pelo progresso desta URL.",
    "zh": "这将用此链接中的进度替换你当前的清单。",
    "hi": "यह आपकी मौजूदा सूची को इस URL की प्रगति से बदल देगा।",
    "ar": "سيؤدي هذا إلى استبدال قائمتك الحالية بالتقدم الموجود في هذا الرابط.",
    "bn": "এটি আপনার বর্তমান তালিকাকে এই URL-এর অগ্রগতি দিয়ে প্রতিস্থাপন করবে।",
    "ru": "Это заменит ваш текущий список прогрессом из этой ссылки.",
    "ja": "現在のチェックリストをこのURLの進行状況で置き換えます。",
    "id": "Ini mengganti daftar periksamu saat ini dengan kemajuan dari URL ini."
  },
  "Done": {
    "en": "Done",
    "cs": "Hotovo",
    "de": "Fertig",
    "es": "Listo",
    "fr": "Terminé",
    "pt": "Concluído",
    "zh": "完成",
    "hi": "पूर्ण",
    "ar": "تم",
    "bn": "সম্পন্ন",
    "ru": "Готово",
    "ja": "完了",
    "id": "Selesai"
  },
  "Import": {
    "en": "Import",
    "cs": "Importovat",
    "de": "Importieren",
    "es": "Importar",
    "fr": "Importer",
    "pt": "Importar",
    "zh": "导入",
    "hi": "आयात करें",
    "ar": "استيراد",
    "bn": "আমদানি করুন",
    "ru": "Импортировать",
    "ja": "インポート",
    "id": "Impor"
  },
  "Progress reset.": {
    "en": "Progress reset.",
    "cs": "Postup resetován.",
    "de": "Fortschritt zurückgesetzt.",
    "es": "Progreso restablecido.",
    "fr": "Progression réinitialisée.",
    "pt": "Progresso redefinido.",
    "zh": "进度已重置。",
    "hi": "प्रगति रीसेट हुई।",
    "ar": "تمت إعادة ضبط التقدم.",
    "bn": "অগ্রগতি রিসেট হয়েছে।",
    "ru": "Прогресс сброшен.",
    "ja": "進行状況をリセットしました。",
    "id": "Kemajuan diatur ulang."
  },
  "Progress imported.": {
    "en": "Progress imported.",
    "cs": "Postup importován.",
    "de": "Fortschritt importiert.",
    "es": "Progreso importado.",
    "fr": "Progression importée.",
    "pt": "Progresso importado.",
    "zh": "进度已导入。",
    "hi": "प्रगति आयात हुई।",
    "ar": "تم استيراد التقدم.",
    "bn": "অগ্রগতি আমদানি হয়েছে।",
    "ru": "Прогресс импортирован.",
    "ja": "進行状況をインポートしました。",
    "id": "Kemajuan diimpor."
  },
  "Invalid progress URL.": {
    "en": "Invalid progress URL.",
    "cs": "Neplatná URL postupu.",
    "de": "Ungültige Fortschritts-URL.",
    "es": "URL de progreso inválida.",
    "fr": "URL de progression invalide.",
    "pt": "URL de progresso inválida.",
    "zh": "进度链接无效。",
    "hi": "प्रगति का URL अमान्य है।",
    "ar": "رابط التقدم غير صالح.",
    "bn": "অগ্রগতির URL অবৈধ।",
    "ru": "Неверная ссылка на прогресс.",
    "ja": "無効な進行状況のURLです。",
    "id": "URL kemajuan tidak valid."
  },
  "Progress URL copied.": {
    "en": "Progress URL copied.",
    "cs": "URL postupu zkopírována.",
    "de": "Fortschritts-URL kopiert.",
    "es": "URL del progreso copiada.",
    "fr": "URL de progression copiée.",
    "pt": "URL do progresso copiada.",
    "zh": "进度链接已复制。",
    "hi": "प्रगति का URL कॉपी हुआ।",
    "ar": "تم نسخ رابط التقدم.",
    "bn": "অগ্রগতির URL কপি হয়েছে।",
    "ru": "Ссылка на прогресс скопирована.",
    "ja": "進行状況のURLをコピーしました。",
    "id": "URL kemajuan disalin."
  },
  "{count} / {total} biomes revealed": {
    "en": {
      "one": "{count} / {total} biome revealed",
      "other": "{count} / {total} biomes revealed"
    },
    "cs": {
      "one": "Odhaleno: {count} biom / {total}",
      "few": "Odhaleno: {count} biomy / {total}",
      "many": "Odhaleno: {count} biomu / {total}",
      "other": "Odhaleno: {count} biomů / {total}"
    },
    "de": {
      "one": "{count} / {total} Biom aufgedeckt",
      "other": "{count} / {total} Biome aufgedeckt"
    },
    "es": {
      "one": "{count} / {total} bioma revelado",
      "many": "{count} / {total} biomas revelados",
      "other": "{count} / {total} biomas revelados"
    },
    "fr": {
      "one": "{count} / {total} biome révélé",
      "many": "{count} / {total} biomes révélés",
      "other": "{count} / {total} biomes révélés"
    },
    "pt": {
      "one": "{count} / {total} bioma revelado",
      "many": "{count} / {total} biomas revelados",
      "other": "{count} / {total} biomas revelados"
    },
    "zh": {
      "other": "已揭示 {count} / {total} 个生物群系"
    },
    "hi": {
      "one": "{count} / {total} बायोम प्रकट",
      "other": "{count} / {total} बायोम प्रकट"
    },
    "ar": {
      "zero": "المناطق المكشوفة: {count} مناطق / {total}",
      "one": "المناطق المكشوفة: {count} منطقة / {total}",
      "two": "المناطق المكشوفة: {count} منطقتان / {total}",
      "few": "المناطق المكشوفة: {count} مناطق / {total}",
      "many": "المناطق المكشوفة: {count} منطقةً / {total}",
      "other": "المناطق المكشوفة: {count} منطقة / {total}"
    },
    "bn": {
      "one": "{count} / {total} বায়োম উন্মোচিত",
      "other": "{count} / {total} বায়োম উন্মোচিত"
    },
    "ru": {
      "one": "Открыто: {count} биом / {total}",
      "few": "Открыто: {count} биома / {total}",
      "many": "Открыто: {count} биомов / {total}",
      "other": "Открыто: {count} биома / {total}"
    },
    "ja": {
      "other": "{count} / {total} バイオーム公開"
    },
    "id": {
      "other": "{count} / {total} bioma terungkap"
    }
  },
  "{count} bosses defeated": {
    "en": {
      "one": "{count} boss defeated",
      "other": "{count} bosses defeated"
    },
    "cs": {
      "one": "Poraženo: {count} boss",
      "few": "Poraženo: {count} bossové",
      "many": "Poraženo: {count} bosse",
      "other": "Poraženo: {count} bossů"
    },
    "de": {
      "one": "{count} Boss besiegt",
      "other": "{count} Bosse besiegt"
    },
    "es": {
      "one": "{count} jefe derrotado",
      "many": "{count} jefes derrotados",
      "other": "{count} jefes derrotados"
    },
    "fr": {
      "one": "{count} boss vaincu",
      "many": "{count} boss vaincus",
      "other": "{count} boss vaincus"
    },
    "pt": {
      "one": "{count} chefe derrotado",
      "many": "{count} chefes derrotados",
      "other": "{count} chefes derrotados"
    },
    "zh": {
      "other": "已击败 {count} 个首领"
    },
    "hi": {
      "one": "{count} बॉस पराजित",
      "other": "{count} बॉस पराजित"
    },
    "ar": {
      "zero": "الزعماء المهزومون: {count} زعماء",
      "one": "الزعماء المهزومون: {count} زعيم",
      "two": "الزعماء المهزومون: {count} زعيمان",
      "few": "الزعماء المهزومون: {count} زعماء",
      "many": "الزعماء المهزومون: {count} زعيمًا",
      "other": "الزعماء المهزومون: {count} زعيم"
    },
    "bn": {
      "one": "{count} বস পরাজিত",
      "other": "{count} বস পরাজিত"
    },
    "ru": {
      "one": "Побеждено: {count} босс",
      "few": "Побеждено: {count} босса",
      "many": "Побеждено: {count} боссов",
      "other": "Побеждено: {count} босса"
    },
    "ja": {
      "other": "{count} ボス討伐"
    },
    "id": {
      "other": "{count} bos dikalahkan"
    }
  }
};
